# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: '~dependabot-approver-template'

# Note: The caller needs to use/provide these in their workflow:
#
# on: pull_request_target
# permissions:
#   pull-requests: write
#   contents: write

on:
  workflow_call:
    inputs:
      max-semver:
        description: "[ignored] The maximum semver level to approve. [options: minor, patch]"
        required: false
        type: string
        default: 'minor'

jobs:
  dependabot:
    runs-on: [ comcast-runner ]
    # Checking the actor will prevent your Action run failing on non-Dependabot
    # PRs but also ensures that it only does work for Dependabot PRs.
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      # The real protection is that the repo builds, runs tests and they succeed.
      - name: Approve a PR & mark for auto apply.
        run: |
          gh pr merge --auto --squash "$PR_URL"
          gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
