# SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: '~docker-release-rebuilder-template'

on:
  workflow_call:
    inputs:
      release-tag:
        description: 'The release tag to rebuild.'
        required: true
        type: string
      latest:
        description: 'If this image should be marked as latest. [DEPRECATED]'
        type: boolean
        default: false
      docker-directory:
        description: 'The directory to look for the docker file.'
        required: false
        type: string
        default: .
      docker-file:
        description: 'The name of the docker file to look for and build.'
        required: false
        type: string
        default: Dockerfile

env:
  WORKFLOW_VERSION: "1.0.0"

defaults:
  run:
    shell: bash

jobs:

  docker:
    runs-on: [ ubuntu-latest ]
    name: Rebuild Docker Image For Existing Release
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release-tag }}

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Image
        run: |
          docker build ${{ inputs.docker-directory }} -f ${{ inputs.docker-file }} \
            --tag ghcr.io/${{ github.repository }}:${{ inputs.release-tag }} \
            --label "org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            --label "org.opencontainers.image.revision=${{ github.sha }}"

      - name: Push Versioned Image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ inputs.release-tag }}
