# SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

name: Meson C Unit Test

on:
  workflow_call:
    inputs:
      packages:
        description: 'The optional list of ubuntu packages to install prior to building.'
        type: string
    secrets:
      sonar_login:
        description: 'The sonarcloud login token.'
        required: true
      token:
        description: 'The GITHUB_TOKEN.'
        required: true

jobs:
  test:
    name: Unit Tests
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update packages
        run: |
          sudo apt update

      - name: Install packages
        run: |
          sudo apt-get -y install python3 python3-pip python3-setuptools python3-wheel \
                                  ninja-build valgrind gcovr \
                                  libcunit1 libcunit1-doc libcunit1-dev \
                                  ${{ inputs.packages }}

      - name: Install Meson
        run: |
          pip3 install --user 'meson>=0.59.0'

      - name: Meson Setup
        run: |
          meson setup --warnlevel 3 --werror build

      - name: Get Sonarcloud Binaries
        uses: xmidt-org/sonarcloud-installer-action@v1
        with:
          working-directory: build

      - name: Build
        working-directory: build
        run: |
          build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw-output ninja all

      - name: Run Tests
        working-directory: build
        run: |
          ninja test

      - name: Generate Coverage Report
        working-directory: build
        run: |
          ninja coverage
          #ninja coverage-sonarqube ## for now this isn't supported
          gcovr --sonarqube sonarqube.xml -r ..

      - name: Upload SonarCloud
        run: |
          build/sonar-scanner/bin/sonar-scanner -Dsonar.host.url=https://sonarcloud.io \
                                                -Dproject.settings=.sonar-project.properties \
                                                -Dsonar.login=${{ secrets.sonar_login }}
        env:
          GITHUB_TOKEN: ${{ secrets.token }}

      - name: Upload Codecov.io
        uses: codecov/codecov-action@v2
        with:
          directory: .
          files: build/meson-logs/coverage.xml
          fail_ci_if_error: true
