# SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  workflow_call:
    inputs:
      meson-provides:
        description: 'The meson package name being provided.'
        type: string
        default: 'none'

jobs:
  release:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Generate Release Bundle
        id: bundle
        uses: xmidt-org/release-builder-action@v3
        with:
          gh-token: ${{ github.token }}
          meson-provides: ${{ inputs.meson-provides }}

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.bundle.outputs.release-name }}
          tag: ${{ steps.bundle.outputs.release-tag }}
          draft: false
          prerelease: false
          bodyFile: ${{ steps.bundle.outputs.release-body-file }}
          artifacts: "${{ steps.bundle.outputs.artifact-dir }}/*"
          token: ${{ github.token }}
